### ISSUE TITLE
Mixins with compound "&" selectors make sourcemaps invalid

### ISSUE THREAD

**Issue by ceph3us** [sass/libsass#2312]
Under a specific set of conditions, compound selectors using `&`, such as `&.mod-enabled` or `&:after`, cause the sourcemap generator to produce sourcemaps with negative column indices.

The conditions are:

- The rule must be a compound selector using the parent selector as above
- The rule must be in the root of a mixin
- The mixin must be included in the document at least 6 times 

This popped up for me when `gulp-sass` switched to version 4.0 of `node-sass`, which pushed LibSass up to 3.4. Smallest reproducible test case I could make is [available here](https://github.com/ceph3us/break-gulp-sass).

Sample error:
```
Error: Invalid mapping: {"generated":{"line":1,"column":6},"source":"mixins.scss","original":{"line":3,"column":-4},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/cepheus/break-gulp-sass/node_modules/source-map/lib/source-map-generator.js:277:13)
    at SourceMapGenerator_addMapping [as addMapping] (/Users/cepheus/break-gulp-sass/node_modules/source-map/lib/source-map-generator.js:101:12)
    at /Users/cepheus/break-gulp-sass/node_modules/concat-with-sourcemaps/index.js:60:28
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/Users/cepheus/break-gulp-sass/node_modules/source-map/lib/source-map-consumer.js:155:14)
    at Concat.add (/Users/cepheus/break-gulp-sass/node_modules/concat-with-sourcemaps/index.js:58:18)
    at DestroyableTransform.bufferContents [as _transform] (/Users/cepheus/break-gulp-sass/node_modules/gulp-concat/index.js:68:12)
    at DestroyableTransform.Transform._read (/Users/cepheus/break-gulp-sass/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/cepheus/break-gulp-sass/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/cepheus/break-gulp-sass/node_modules/readable-stream/lib/_stream_writable.js:347:64)
```

A bisection of the test case revealed this issue was introduced in commit de83d30.

**Comment by ceph3us** [comment]
CCing in dlmanning/gulp-sass#577 so this issue is linked to that one.

**Comment by mgreter** [comment]
Thanks for the test case, I can confirm the issue [live from your repo with my sourcemap inspector][1]. 

![grafik](https://cloud.githubusercontent.com/assets/282293/22581664/202f4f20-e9e2-11e6-9025-327352a18533.png)

[1]: http://libsass.ocbnet.ch/srcmap/#QGltcG9ydCAiaHR0cDovL2Nkbi5yYXdnaXQuY29tL2NlcGgzdXMvYnJlYWstZ3VscC1zYXNzL21hc3Rlci9hcHAvYXNzZXRzL3Nhc3MvbWl4aW5zLnNjc3MiOwo=

**Comment by KevinBusch** [comment]
Any update on this?

**Comment by hvalcourtSerdy** [comment]
I have the Invalid mapping error and I dont use gulp. (node-sass)

**Comment by DBosley** [comment]
Getting an issue related to this combined with @angular/material2's styles. Commenting here to raise awareness of the issue.

**Comment by mahnunchik** [comment]
Any news?

**Comment by jmharveys** [comment]
What is happening with this issue? There's no fix into the lib....

**Comment by testgit-1** [comment]
Any news?

**Comment by aussisimple** [comment]
I have the same problem
