### ISSUE TITLE
fatal error LNK1107: invalid or corrupt file: cannot read at 0xB8790

### ISSUE THREAD

**Issue by ClarenceC** [sass/libsass#2433]
I can't install node-sass,
when i install use 'npm install node-sass --save-dev',it will happen Error.

## Actual results

`C:\Users\Administrator\.node-gyp\7.10.0\x64\node.lib : fatal error LNK1107: invalid or corrupt file: cannot read at 0xB8790 [D:\Project\ GitRepositorys\awesome-TPC\node_modules\node-sass\build\binding.vcxproj]`

```
C:\Users\Administrator\.node-gyp\7.10.0\x64\node.lib : fatal error LNK1107: invalid or corrupt file: cannot read at 0xB8790 [D:\Project\ GitRepositorys\awesome-TPC\node_modules\node-sass\build\binding.vcxproj]
已完成生成项目“D:\Project\GitRepositorys\awesome-TPC\node_modules\node-sass\build\binding.vcxproj”(默认目标)的操作 - 失败。

已完成生成项目“D:\Project\GitRepositorys\awesome-TPC\node_modules\node-sass\build\binding.vcxproj.metaproj”(默认目标)的操作 - 失败。

已完成生成项目“D:\Project\GitRepositorys\awesome-TPC\node_modules\node-sass\build\binding.sln”(默认目标)的操作 - 失败。


生成失败。

“D:\Project\GitRepositorys\awesome-TPC\node_modules\node-sass\build\binding.sln”(默认目标) (1) ->
“D:\Project\GitRepositorys\awesome-TPC\node_modules\node-sass\build\binding.vcxproj.metaproj”(默认目标) (2) ->
“D:\Project\GitRepositorys\awesome-TPC\node_modules\node-sass\build\binding.vcxproj”(默认目标) (4) ->
(Link 目标) ->
  C:\Users\Administrator\.node-gyp\7.10.0\x64\node.lib : fatal error LNK1107: invalid or corrupt file: cannot read at 0xB8790 [D:\Projec t\GitRepositorys\awesome-TPC\node_modules\node-sass\build\binding.vcxproj]

    11 个警告
    1 个错误

已用时间 00:00:44.69
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Project\GitRepositorys\awesome-TPC\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Project\\GitRepositorys\\awesome-TPC\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\Project\GitRepositorys\awesome-TPC\node_modules\node-sass
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1


```
version info:
```
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Project\GitRepositorys\awesome-TPC\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Project\\GitRepositorys\\awesome-TPC\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\Project\GitRepositorys\awesome-TPC\node_modules\node-sass
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.0.17 (node_modules\react-scripts\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "node-sass" "--save-dev"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.3 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-07-07T06_29_08_819Z-debug.log
```

[2017-07-07T06_29_08_819Z-debug.txt](https://github.com/sass/libsass/files/1130178/2017-07-07T06_29_08_819Z-debug.txt)

**Comment by xzyfer** [comment]
Please open this on the node-sass issue track by following the issue template.
