### ISSUE TITLE
npm ERR! missing: node-sass@^4.2.0, required by gulp-sass@3.1.0

### ISSUE THREAD

**Issue by NeerajVashishth1** [sass/libsass#2475]
[ERROR] Gulpfile (or dependent module) not found: ./gulpfile.js

        For custom Gulpfile locations, you can run ionic config set gulp.file <path>. Otherwise, the default Ionic 
        Gulpfile can be downloaded from https://github.com/ionic-team/ionic-app-base/blob/master/gulpfile.js
        
        Or, if you don't use gulp, you can disable it by running ionic config set gulp.enabled false.
        Full error:
        
        Error: Cannot find module 'node-sass'
            at Function.Module._resolveFilename (module.js:469:15)
            at Function.Module._load (module.js:417:25)
            at Module.require (module.js:497:17)
            at require (internal/module.js:20:19)
            at Object.<anonymous> (/home/neeraj/knowlarity_mobile_app/node_modules/gulp-sass/index.js:187:21)
            at Module._compile (module.js:570:32)
            at Object.Module._extensions..js (module.js:579:10)
            at Module.load (module.js:487:32)
            at tryModuleLoad (module.js:446:12)
            at Function.Module._load (module.js:438:3)

**Comment by xzyfer** [comment]
This is not a libsass issue. Open an issue with iconic.
