### ISSUE TITLE
AddressSanitizer: stack-overflow at Sass::Compound_Selector::operator== (ast.cpp:1058)

### ISSUE THREAD

**Issue by HongxuChen** [sass/libsass#2667]
We found with our fuzzer some stack over flow errors when creating temp selector objects at Line 1508 in ast.cpp (45f50873962b7d1c66bd115ba6e644bdaaf6cac1) when compiled with Address Sanitizer (using sassc as the driver).

```
ASAN:SIGSEGV
=================================================================
==20277==ERROR: AddressSanitizer: stack-overflow on address 0x7ffdc834dfd8 (pc 0x7f37e2a4d80b bp 0x7ffdc834e8e0 sp 0x7ffdc834dfd0 T0)
    #0 0x7f37e2a4d80a  (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x2280a)
    #1 0x7f37e2ac44fe in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x994fe)
    #2 0x7f37e23f6790 in __gnu_cxx::new_allocator<Sass::SharedImpl<Sass::Simple_Selector> >::allocate(unsigned long, void const*) /usr/include/c++/5/ext/new_allocator.h:104
    #3 0x7f37e23f6790 in std::allocator_traits<std::allocator<Sass::SharedImpl<Sass::Simple_Selector> > >::allocate(std::allocator<Sass::SharedImpl<Sass::Simple_Selector> >&, unsigned long) /usr/include/c++/5/bits/alloc_traits.h:491
    #4 0x7f37e23f6790 in std::_Vector_base<Sass::SharedImpl<Sass::Simple_Selector>, std::allocator<Sass::SharedImpl<Sass::Simple_Selector> > >::_M_allocate(unsigned long) /usr/include/c++/5/bits/stl_vector.h:170
    #5 0x7f37e23f6790 in std::_Vector_base<Sass::SharedImpl<Sass::Simple_Selector>, std::allocator<Sass::SharedImpl<Sass::Simple_Selector> > >::_M_create_storage(unsigned long) /usr/include/c++/5/bits/stl_vector.h:185
    #6 0x7f37e23f6790 in std::_Vector_base<Sass::SharedImpl<Sass::Simple_Selector>, std::allocator<Sass::SharedImpl<Sass::Simple_Selector> > >::_Vector_base(unsigned long, std::allocator<Sass::SharedImpl<Sass::Simple_Selector> > const&) /usr/include/c++/5/bits/stl_vector.h:136
    #7 0x7f37e23f6790 in std::vector<Sass::SharedImpl<Sass::Simple_Selector>, std::allocator<Sass::SharedImpl<Sass::Simple_Selector> > >::vector(std::vector<Sass::SharedImpl<Sass::Simple_Selector>, std::allocator<Sass::SharedImpl<Sass::Simple_Selector> > > const&) /usr/include/c++/5/bits/stl_vector.h:320
    #8 0x7f37e23f6790 in Sass::Compound_Selector::operator==(Sass::Compound_Selector const&) const /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:1058
    #9 0x7f37e23b07e1 in Sass::Complex_Selector::operator<(Sass::Complex_Selector const&) const /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:248
    #10 0x7f37e2426da0 in bool Sass::OrderNodes::operator()<Sass::SharedImpl<Sass::Complex_Selector> >(Sass::SharedImpl<Sass::Complex_Selector> const&, Sass::SharedImpl<Sass::Complex_Selector> const&) const /home/hongxu/FUZZ/libsass-orig/src/ast_fwd_decl.hpp:375
    #11 0x7f37e2426da0 in bool __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes>::operator()<__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > > >(__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >) /usr/include/c++/5/bits/predefined_ops.h:123
    #12 0x7f37e2426da0 in void std::__insertion_sort<__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes> >(__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes>) /usr/include/c++/5/bits/stl_algo.h:1842
    #13 0x7f37e242708c in void std::__final_insertion_sort<__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes> >(__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes>) /usr/include/c++/5/bits/stl_algo.h:1885
    #14 0x7f37e23f756a in void std::__sort<__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes> >(__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes>) /usr/include/c++/5/bits/stl_algo.h:1966
    #15 0x7f37e23f756a in void std::sort<__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, Sass::OrderNodes>(__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, Sass::OrderNodes) /usr/include/c++/5/bits/stl_algo.h:4729
...
    #433 0x7f37e242708c in void std::__final_insertion_sort<__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes> >(__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes>) /usr/include/c++/5/bits/stl_algo.h:1885
    #434 0x7f37e23f75bb in void std::__sort<__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes> >(__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes>) /usr/include/c++/5/bits/stl_algo.h:1966
    #435 0x7f37e23f75bb in void std::sort<__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, Sass::OrderNodes>(__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, Sass::OrderNodes) /usr/include/c++/5/bits/stl_algo.h:4729
    #436 0x7f37e23f75bb in Sass::Selector_List::operator==(Sass::Selector_List const&) const /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:470
```

Sample inputs:
[so_ast.cpp:1058_01.txt](https://github.com/sass/libsass/files/2065638/so_ast.cpp.1058_01.txt)
[so_ast.cpp:1058_02.txt](https://github.com/sass/libsass/files/2065639/so_ast.cpp.1058_02.txt)
[so_ast.cpp:1058_03.txt](https://github.com/sass/libsass/files/2065640/so_ast.cpp.1058_03.txt)

**Comment by glebm** [comment]
This is fixed on the current master (not sure by which commit).
