### ISSUE TITLE
AddressSanitizer: stack-overflow at Sass::Simple_Selector::is_ns_eq (ast.cpp:145)

### ISSUE THREAD

**Issue by HongxuChen** [sass/libsass#2668]
We found with our fuzzer some stack over flow errors at Sass::Simple_Selector::is_ns_eq (ast.cpp:145) (45f50873962b7d1c66bd115ba6e644bdaaf6cac1) when compiled with Address Sanitizer (using sassc as the driver).

```
ASAN:SIGSEGV
=================================================================
==22323==ERROR: AddressSanitizer: stack-overflow on address 0x7ffcfbeebfe8 (pc 0x7fa7ffb5a1a4 bp 0x7ffcfbeec860 sp 0x7ffcfbeebff0 T0)
    #0 0x7fa7ffb5a1a3 in __interceptor_strlen (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x701a3)
    #1 0x7fa7fe3f643b in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x12143b)
    #2 0x7fa7ff48eb3f in bool std::operator==<char, std::char_traits<char>, std::allocator<char> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*) /usr/include/c++/5/bits/basic_string.h:4939
    #3 0x7fa7ff48eb3f in Sass::Simple_Selector::is_ns_eq(Sass::Simple_Selector const&) const /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:145
    #4 0x7fa7ff48edf2 in Sass::Element_Selector::operator<(Sass::Element_Selector const&) const /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:714
    #5 0x7fa7ff4e655b in bool Sass::OrderNodes::operator()<Sass::SharedImpl<Sass::Simple_Selector> >(Sass::SharedImpl<Sass::Simple_Selector> const&, Sass::SharedImpl<Sass::Simple_Selector> const&) const /home/hongxu/FUZZ/libsass-orig/src/ast_fwd_decl.hpp:375
    #6 0x7fa7ff4e655b in bool __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes>::operator()<__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Simple_Selector>*, std::vector<Sass::SharedImpl<Sass::Simple_Selector>, std::allocator<Sass::SharedImpl<Sass::Simple_Selector> > > >, __gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Simple_Selector>*, std::vector<Sass::SharedImpl<Sass::Simple_Selector>, std::allocator<Sass::SharedImpl<Sass::Simple_Selector> > > > >(__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Simple_Selector>*, std::vector<Sass::SharedImpl<Sass::Simple_Selector>, std::allocator<Sass::SharedImpl<Sass::Simple_Selector> > > >, __gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Simple_Selector>*, std::vector<Sass::SharedImpl<Sass::Simple_Selector>, std::allocator<Sass::SharedImpl<Sass::Simple_Selector> > > >) /usr/include/c++/5/bits/predefined_ops.h:123
    #7 0x7fa7ff4e655b in void std::__insertion_sort<__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Simple_Selector>*, std::vector<Sass::SharedImpl<Sass::Simple_Selector>, std::allocator<Sass::SharedImpl<Sass::Simple_Selector> > > >, __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes> >(__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Simple_Selector>*, std::vector<Sass::SharedImpl<Sass::Simple_Selector>, std::allocator<Sass::SharedImpl<Sass::Simple_Selector> > > >, __gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Simple_Selector>*, std::vector<Sass::SharedImpl<Sass::Simple_Selector>, std::allocator<Sass::SharedImpl<Sass::Simple_Selector> > > >, __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes>) /usr/include/c++/5/bits/stl_algo.h:1842
    #8 0x7fa7ff4e681c in void std::__final_insertion_sort<__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Simple_Selector>*, std::vector<Sass::SharedImpl<Sass::Simple_Selector>, std::allocator<Sass::SharedImpl<Sass::Simple_Selector> > > >, __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes> >(__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Simple_Selector>*, std::vector<Sass::SharedImpl<Sass::Simple_Selector>, std::allocator<Sass::SharedImpl<Sass::Simple_Selector> > > >, __gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Simple_Selector>*, std::vector<Sass::SharedImpl<Sass::Simple_Selector>, std::allocator<Sass::SharedImpl<Sass::Simple_Selector> > > >, __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes>) /usr/include/c++/5/bits/stl_algo.h:1885
    #9 0x7fa7ff4b5a8b in void std::__sort<__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Simple_Selector>*, std::vector<Sass::SharedImpl<Sass::Simple_Selector>, std::allocator<Sass::SharedImpl<Sass::Simple_Selector> > > >, __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes> >(__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Simple_Selector>*, std::vector<Sass::SharedImpl<Sass::Simple_Selector>, std::allocator<Sass::SharedImpl<Sass::Simple_Selector> > > >, __gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Simple_Selector>*, std::vector<Sass::SharedImpl<Sass::Simple_Selector>, std::allocator<Sass::SharedImpl<Sass::Simple_Selector> > > >, __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes>) /usr/include/c++/5/bits/stl_algo.h:1966
    #10 0x7fa7ff4b5a8b in void std::sort<__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Simple_Selector>*, std::vector<Sass::SharedImpl<Sass::Simple_Selector>, std::allocator<Sass::SharedImpl<Sass::Simple_Selector> > > >, Sass::OrderNodes>(__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Simple_Selector>*, std::vector<Sass::SharedImpl<Sass::Simple_Selector>, std::allocator<Sass::SharedImpl<Sass::Simple_Selector> > > >, __gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Simple_Selector>*, std::vector<Sass::SharedImpl<Sass::Simple_Selector>, std::allocator<Sass::SharedImpl<Sass::Simple_Selector> > > >, Sass::OrderNodes) /usr/include/c++/5/bits/stl_algo.h:4729
    #11 0x7fa7ff4b5a8b in Sass::Compound_Selector::operator==(Sass::Compound_Selector const&) const /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:1061
    #12 0x7fa7ff46f7e1 in Sass::Complex_Selector::operator<(Sass::Complex_Selector const&) const /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:248
    #13 0x7fa7ff4e5da0 in bool Sass::OrderNodes::operator()<Sass::SharedImpl<Sass::Complex_Selector> >(Sass::SharedImpl<Sass::Complex_Selector> const&, Sass::SharedImpl<Sass::Complex_Selector> const&) const /home/hongxu/FUZZ/libsass-orig/src/ast_fwd_decl.hpp:375
    #14 0x7fa7ff4e5da0 in bool __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes>::operator()<__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > > >(__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >) /usr/include/c++/5/bits/predefined_ops.h:123
    #15 0x7fa7ff4e5da0 in void std::__insertion_sort<__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes> >(__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes>) /usr/include/c++/5/bits/stl_algo.h:1842
    #16 0x7fa7ff4e608c in void std::__final_insertion_sort<__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes> >(__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes>) /usr/include/c++/5/bits/stl_algo.h:1885
    #17 0x7fa7ff4b656a in void std::__sort<__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes> >(__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__ops::_Iter_comp_iter<Sass::OrderNodes>) /usr/include/c++/5/bits/stl_algo.h:1966
    #18 0x7fa7ff4b656a in void std::sort<__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, Sass::OrderNodes>(__gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, __gnu_cxx::__normal_iterator<Sass::SharedImpl<Sass::Complex_Selector>*, std::vector<Sass::SharedImpl<Sass::Complex_Selector>, std::allocator<Sass::SharedImpl<Sass::Complex_Selector> > > >, Sass::OrderNodes) /usr/include/c++/5/bits/stl_algo.h:4729
    #19 0x7fa7ff4b656a in Sass::Selector_List::operator==(Sass::Selector_List const&) const /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:469
    #20 0x7fa7ff4976fa in Sass::Wrapped_Selector::operator==(Sass::Wrapped_Selector const&) const /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:797
    #21 0x7fa7ff4b5b07 in Sass::Simple_Selector::operator!=(Sass::Simple_Selector const&) const /home/hongxu/FUZZ/libsass-orig/src/ast.hpp:2364
    #22 0x7fa7ff4b5b07 in Sass::Compound_Selector::operator==(Sass::Compound_Selector const&) const /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:1075
    #23 0x7fa7ff471659 in Sass::Complex_Selector::operator==(Sass::Complex_Selector const&) const /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:317
    #24 0x7fa7ff4b6637 in Sass::Complex_Selector::operator!=(Sass::Complex_Selector const&) const /home/hongxu/FUZZ/libsass-orig/src/ast.hpp:2855
    #25 0x7fa7ff4b6637 in Sass::Selector_List::operator==(Sass::Selector_List const&) const /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:484
    #26 0x7fa7ff4976fa in Sass::Wrapped_Selector::operator==(Sass::Wrapped_Selector const&) const /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:797
    #27 0x7fa7ff4b5b07 in Sass::Simple_Selector::operator!=(Sass::Simple_Selector const&) const /home/hongxu/FUZZ/libsass-orig/src/ast.hpp:2364
...
    #377 0x7fa7ff471659 in Sass::Complex_Selector::operator==(Sass::Complex_Selector const&) const /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:317
    #378 0x7fa7ff4b6637 in Sass::Complex_Selector::operator!=(Sass::Complex_Selector const&) const /home/hongxu/FUZZ/libsass-orig/src/ast.hpp:2855
    #379 0x7fa7ff4b6637 in Sass::Selector_List::operator==(Sass::Selector_List const&) const /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:484
    #380 0x7fa7ff4976fa in Sass::Wrapped_Selector::operator==(Sass::Wrapped_Selector const&) const /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:797

SUMMARY: AddressSanitizer: stack-overflow ??:0 __interceptor_strlen
==22323==ABORTING
```

Sample inputs:
[so_ast.cpp:145_02.txt](https://github.com/sass/libsass/files/2065643/so_ast.cpp.145_02.txt)
[so_ast.cpp:145_03.txt](https://github.com/sass/libsass/files/2065644/so_ast.cpp.145_03.txt)

**Comment by glebm** [comment]
This is also fixed on the current master, likely by one of the invalid comparison function fixes.
