### ISSUE TITLE
AddressSanitizer: stack-overflow at Sass::Simple_Selector::ns_name[abi:cxx11] (ast.hpp, inspect.cpp:929)

### ISSUE THREAD

**Issue by HongxuChen** [sass/libsass#2669]
We found with our fuzzer some stack over flow errors Sass::Simple_Selector::ns_name (ast.hpp, inspect.cpp:929)  (45f50873962b7d1c66bd115ba6e644bdaaf6cac1) when compiled with Address Sanitizer (using sassc as the driver).

```
ASAN:SIGSEGV
=================================================================
==1609==ERROR: AddressSanitizer: stack-overflow on address 0x7fffb645eef8 (pc 0x7f0fe4a475cf bp 0x7fffb645f770 sp 0x7fffb645ef00 T0)
    #0 0x7f0fe4a475ce in __asan_memcpy (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x8c5ce)
    #1 0x7f0fe4677c27 in std::char_traits<char>::copy(char*, char const*, unsigned long) /usr/include/c++/5/bits/char_traits.h:290
    #2 0x7f0fe4677c27 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy(char*, char const*, unsigned long) /usr/include/c++/5/bits/basic_string.h:299
    #3 0x7f0fe4677c27 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy_chars(char*, char*, char*) /usr/include/c++/5/bits/basic_string.h:341
    #4 0x7f0fe4677c27 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) /usr/include/c++/5/bits/basic_string.tcc:229
    #5 0x7f0fe468264a in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct_aux<char*>(char*, char*, std::__false_type) /usr/include/c++/5/bits/basic_string.h:195
    #6 0x7f0fe468264a in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*) /usr/include/c++/5/bits/basic_string.h:214
    #7 0x7f0fe468264a in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/include/c++/5/bits/basic_string.h:400
    #8 0x7f0fe468264a in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*) /usr/include/c++/5/bits/basic_string.h:4823
    #9 0x7f0fe468264a in Sass::Simple_Selector::ns_name[abi:cxx11]() const /home/hongxu/FUZZ/libsass-orig/src/ast.hpp:2309
    #10 0x7f0fe468264a in Sass::Inspect::operator()(Sass::Element_Selector*) /home/hongxu/FUZZ/libsass-orig/src/inspect.cpp:929
    #11 0x7f0fe4677e50 in Sass::Inspect::operator()(Sass::Compound_Selector*) /home/hongxu/FUZZ/libsass-orig/src/inspect.cpp:996
    #12 0x7f0fe4685ed7 in Sass::Compound_Selector::perform(Sass::Operation<void>*) /home/hongxu/FUZZ/libsass-orig/src/ast.hpp:2742
    #13 0x7f0fe4685ed7 in Sass::Inspect::operator()(Sass::Complex_Selector*) /home/hongxu/FUZZ/libsass-orig/src/inspect.cpp:1023
    #14 0x7f0fe468863b in Sass::Complex_Selector::perform(Sass::Operation<void>*) /home/hongxu/FUZZ/libsass-orig/src/ast.hpp:2907
    #15 0x7f0fe468863b in Sass::Inspect::operator()(Sass::Selector_List*) /home/hongxu/FUZZ/libsass-orig/src/inspect.cpp:1098
    #16 0x7f0fe467deb3 in Sass::Selector_List::perform(Sass::Operation<void>*) /home/hongxu/FUZZ/libsass-orig/src/ast.hpp:2984
...
    #457 0x7f0fe467deb3 in Sass::Inspect::operator()(Sass::Wrapped_Selector*) /home/hongxu/FUZZ/libsass-orig/src/inspect.cpp:986
    #458 0x7f0fe4677e50 in Sass::Inspect::operator()(Sass::Compound_Selector*) /home/hongxu/FUZZ/libsass-orig/src/inspect.cpp:996
    #459 0x7f0fe4685ed7 in Sass::Compound_Selector::perform(Sass::Operation<void>*) /home/hongxu/FUZZ/libsass-orig/src/ast.hpp:2742
    #460 0x7f0fe4685ed7 in Sass::Inspect::operator()(Sass::Complex_Selector*) /home/hongxu/FUZZ/libsass-orig/src/inspect.cpp:1023
    #461 0x7f0fe46863f4 in Sass::Complex_Selector::perform(Sass::Operation<void>*) /home/hongxu/FUZZ/libsass-orig/src/ast.hpp:2907
    #462 0x7f0fe46863f4 in Sass::Inspect::operator()(Sass::Complex_Selector*) /home/hongxu/FUZZ/libsass-orig/src/inspect.cpp:1061

SUMMARY: AddressSanitizer: stack-overflow ??:0 __asan_memcpy
==1609==ABORTING
```

Sampe input files:
[so_ast.hpp:2309_01.txt](https://github.com/sass/libsass/files/2065657/so_ast.hpp.2309_01.txt)
[so_ast.hpp:2309_02.txt](https://github.com/sass/libsass/files/2065658/so_ast.hpp.2309_02.txt)
[so_ast.hpp:2309_03.txt](https://github.com/sass/libsass/files/2065659/so_ast.hpp.2309_03.txt)
[so_ast.hpp:2310_01.txt](https://github.com/sass/libsass/files/2065660/so_ast.hpp.2310_01.txt)
[so_ast.hpp:2310_02.txt](https://github.com/sass/libsass/files/2065661/so_ast.hpp.2310_02.txt)
[so_ast.hpp:2310_03.txt](https://github.com/sass/libsass/files/2065662/so_ast.hpp.2310_03.txt)
[so_inspect.cpp:929_01.txt](https://github.com/sass/libsass/files/2065667/so_inspect.cpp.929_01.txt)

**Comment by glebm** [comment]
This is also fixed on the current master:

Output for each test file:

```
Error: Invalid CSS after "e": expected selector, was "(1,"
        on line 1:13 of ../../../Downloads/so_ast.hpp.2309_01.txt
>> :not(*ct|*y
   ------------^
Error: Invalid CSS after "e": expected selector, was "(1,"
        on line 1:13 of ../../../Downloads/so_ast.hpp.2309_02.txt
>> :not(*ct|*y
   ------------^
Error: Invalid CSS after "e": expected selector, was "(1,"
        on line 1:13 of ../../../Downloads/so_ast.hpp.2309_03.txt
>> :not(*ct|*y
   ------------^
Error: Invalid CSS after "e": expected selector, was "(1,"
        on line 1:13 of ../../../Downloads/so_ast.hpp.2310_01.txt
>> :not(*ct|*y
   ------------^
Error: Invalid CSS after "e": expected selector, was "(1,"
        on line 1:13 of ../../../Downloads/so_ast.hpp.2310_02.txt
>> :not(*ct|*y
   ------------^
Error: Invalid CSS after "e": expected selector, was "(1,"
        on line 1:13 of ../../../Downloads/so_ast.hpp.2310_03.txt
>> :not(*ct|*y
   ------------^
Error: Invalid CSS after "e": expected selector, was "(1,"
        on line 1:13 of ../../../Downloads/so_inspect.cpp.929_01.txt
>> :not(*ct|*y
   ------------^
```
