### ISSUE TITLE
AddressSanitizer: stack-overflow at Sass::hasNotSelector (eval.cpp:1626)

### ISSUE THREAD

**Issue by HongxuChen** [sass/libsass#2670]
We found with our fuzzer a some stack over flow error at Sass::hasNotSelector(Sass::SharedImpl<Sass::AST_Node>) eval.cpp:1626 (45f50873962b7d1c66bd115ba6e644bdaaf6cac1) when compiled with Address Sanitizer (using sassc as the driver).

```
==2260==ERROR: AddressSanitizer: stack-overflow on address 0x7ffd08fabd58 (pc 0x7fab657fe1a4 bp 0x7ffd08fac5d0 sp 0x7ffd08fabd60 T0)
    #0 0x7fab657fe1a3 in __interceptor_strlen (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x701a3)
    #1 0x7fab6409a43b in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x12143b)
    #2 0x7fab65361a31 in bool std::operator==<char, std::char_traits<char>, std::allocator<char> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*) /usr/include/c++/5/bits/basic_string.h:4939
    #3 0x7fab65361a31 in Sass::hasNotSelector(Sass::SharedImpl<Sass::AST_Node>) /home/hongxu/FUZZ/libsass-orig/src/eval.cpp:1626
    #4 0x7fab65113b30 in Sass::Wrapped_Selector::find(bool (*)(Sass::SharedImpl<Sass::AST_Node>)) /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:29
    #5 0x7fab651142ff in Sass::Compound_Selector::find(bool (*)(Sass::SharedImpl<Sass::AST_Node>)) /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:46
    #6 0x7fab65112db6 in Sass::Complex_Selector::find(bool (*)(Sass::SharedImpl<Sass::AST_Node>)) /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:55
    #7 0x7fab65112e37 in Sass::Complex_Selector::find(bool (*)(Sass::SharedImpl<Sass::AST_Node>)) /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:56
    #8 0x7fab65113fff in Sass::Selector_List::find(bool (*)(Sass::SharedImpl<Sass::AST_Node>)) /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:36
    #9 0x7fab65113b06 in Sass::Wrapped_Selector::find(bool (*)(Sass::SharedImpl<Sass::AST_Node>)) /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:26
    #10 0x7fab651142ff in Sass::Compound_Selector::find(bool (*)(Sass::SharedImpl<Sass::AST_Node>)) /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:46
    #11 0x7fab65112db6 in Sass::Complex_Selector::find(bool (*)(Sass::SharedImpl<Sass::AST_Node>)) /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:55
    #12 0x7fab65112e37 in Sass::Complex_Selector::find(bool (*)(Sass::SharedImpl<Sass::AST_Node>)) /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:56
    #13 0x7fab65113fff in Sass::Selector_List::find(bool (*)(Sass::SharedImpl<Sass::AST_Node>)) /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:36
    #14 0x7fab65113b06 in Sass::Wrapped_Selector::find(bool (*)(Sass::SharedImpl<Sass::AST_Node>)) /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:26
...
    #249 0x7fab651142ff in Sass::Compound_Selector::find(bool (*)(Sass::SharedImpl<Sass::AST_Node>)) /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:46
    #250 0x7fab65112db6 in Sass::Complex_Selector::find(bool (*)(Sass::SharedImpl<Sass::AST_Node>)) /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:55
    #251 0x7fab65113fff in Sass::Selector_List::find(bool (*)(Sass::SharedImpl<Sass::AST_Node>)) /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:36
    #252 0x7fab65113b06 in Sass::Wrapped_Selector::find(bool (*)(Sass::SharedImpl<Sass::AST_Node>)) /home/hongxu/FUZZ/libsass-orig/src/ast.cpp:26

SUMMARY: AddressSanitizer: stack-overflow ??:0 __interceptor_strlen
==2260==ABORTING
```

Sample input file:
[so_eval.cpp:1626_01.txt](https://github.com/sass/libsass/files/2065673/so_eval.cpp.1626_01.txt)

**Comment by HongxuChen** [comment]
Two relevant inputs:
[so_ast.cpp:43_01.txt](https://github.com/sass/libsass/files/2101571/so_ast.cpp.43_01.txt)
[so_ast.cpp:45_01.txt](https://github.com/sass/libsass/files/2101572/so_ast.cpp.45_01.txt)

**Comment by glebm** [comment]
This is fixed on the current master.
