### ISSUE TITLE
Build on Ubuntu 14.04.5 / 18.04.2  LTS fails due make error

### ISSUE THREAD

**Issue by Simonwep** [sass/libsass#2883]
It's actually a build error, not an issue with the tool itself so sorry for not using the issue template.
Libsass is used in a projects using node-sass `4.11.0` (also tried with `4.9`). Tried to build it on Ubuntu `Ubuntu 18.04.2 LTS` and `14.04.5`.

The entire log is available here: https://travis-ci.org/Simonwep/candy/builds/525326689 It's pretty large so I wont post it here. The point where the build fails:

```
.... many lines
 g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/home/travis/.node-gyp/12.0.0/include/node -I/home/travis/.node-gyp/12.0.0/src -I/home/travis/.node-gyp/12.0.0/deps/openssl/config -I/home/travis/.node-gyp/12.0.0/deps/openssl/openssl/include -I/home/travis/.node-gyp/12.0.0/deps/uv/include -I/home/travis/.node-gyp/12.0.0/deps/zlib -I/home/travis/.node-gyp/12.0.0/deps/v8/include -I../../nan -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/create_string.o.d.raw   -c -o Release/obj.target/binding/src/create_string.o ../src/create_string.cpp
../src/create_string.cpp: In function ‘char* create_string(Nan::MaybeLocal<v8::Value>)’:
../src/create_string.cpp:17:37: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>&)’
   v8::String::Utf8Value string(value);
                                     ^
../src/create_string.cpp:17:37: note: candidate is:
In file included from /home/travis/.node-gyp/12.0.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:53,
                 from ../src/create_string.cpp:1:
/home/travis/.node-gyp/12.0.0/include/node/v8.h:2995:5: note: v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)
     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
     ^
/home/travis/.node-gyp/12.0.0/include/node/v8.h:2995:5: note:   candidate expects 2 arguments, 1 provided
make: *** [Release/obj.target/binding/src/create_string.o] Error 1
make: Leaving directory `/home/travis/build/Simonwep/candy/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/build/Simonwep/candy/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Linux 4.4.0-101-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v12.0.0/bin/node" "/home/travis/build/Simonwep/candy/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/travis/build/Simonwep/candy/node_modules/node-sass
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
.... npm errored
```

System(s):
```
Platform: Ubuntu v14.04.5 LTS and  v18.04.2 LTS
Node:  v12.0.0
NPM: v6.9.0

make -v:
GNU Make 4.1
Built for x86_64-pc-linux-gnu
```

It's works on windows 10, using node `v10.15.03` and npm `v6.9.0`.
Sorry again if this issue is kida uncomplete, I'll tried to provide as much informations as possible. I'm also not really familiar with c++ so excuse if there's a catch I don't get.

**Comment by glebm** [comment]
The error you are seeing is not libsass code. Looks like it's in node-sass code, I suggest reporting the issue there.

**Comment by xzyfer** [comment]
This is an older version of nan. Update to node-sass@4.12.0

**Comment by Simonwep** [comment]
Lol, `node-sass@4.12.0` wasn't available until today on npm. With it it works. Okay, thank's anyway.

**Comment by ladifire** [comment]
node-sass 4.14.1 still error.
