### ISSUE TITLE
Null Pointer Dereference in cssize.cpp

### ISSUE THREAD

**Issue by LyleMi** [sass/libsass#3063]
Hi, I found a Null Pointer Dereference bug in ``cssize.cpp`` with commit ``3e73baee``, compiled with clang 8 and address sanitizer.

You could trigger it by following command:

```bash
echo "QGltcG9ydDZ1cmUtcGF0aDphIHsKIHBvcnQzdXJlLXBhdGg6YSB7CiAgQGF0LXJvb3QgYjogYzsKICB9Cgp9Cg==" | base64 -d | ./sassc/bin/sassc
```

```
ASAN:SIGSEGV
=================================================================
==3955==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000627020 bp 0x7ffd42283500 sp 0x7ffd422832e0 T0)
    #0 0x62701f in Sass::Cssize::bubblable(Sass::Statement*) src/cssize.cpp:383
    sass/sassc#1 0x632bb2 in Sass::Cssize::operator()(Sass::StyleRule*) src/cssize.cpp:204
    sass/sassc#2 0x62abaf in Sass::Cssize::append_block(Sass::Block*, Sass::Block*) src/cssize.cpp:508
    sass/sassc#3 0x62b877 in Sass::Cssize::operator()(Sass::Block*) src/cssize.cpp:30
    sass/sassc#4 0x63b3e1 in Sass::Cssize::operator()(Sass::AtRule*) src/cssize.cpp:93
    sass/sassc#5 0x62abaf in Sass::Cssize::append_block(Sass::Block*, Sass::Block*) src/cssize.cpp:508
    sass/sassc#6 0x62b877 in Sass::Cssize::operator()(Sass::Block*) src/cssize.cpp:30
    sass/sassc#7 0x43da0c in Sass::Context::compile() src/context.cpp:664
    sass/sassc#8 0x440d19 in Sass::File_Context::parse() src/context.cpp:582
    sass/sassc#9 0x428669 in sass_parse_block src/sass_context.cpp:181
    sass/sassc#10 0x428669 in sass_compiler_parse src/sass_context.cpp:435
    sass/sassc#11 0x4291f8 in sass_compile_context src/sass_context.cpp:318
    sass/sassc#12 0x420e65 in compile_file /home/ubuntu/sassc/sassc.c:173
    sass/sassc#13 0x409b9f in main /home/ubuntu/sassc/sassc.c:387
    sass/sassc#14 0x7fb9beb5e82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    sass/sassc#15 0x420868 in _start (/home/ubuntu/sassc/bin/sassc+0x420868)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV src/cssize.cpp:383 Sass::Cssize::bubblable(Sass::Statement*)
==3955==ABORTING
```

**Comment by nschonni** [comment]
I've moved this over to libsass. Can you try and reproduce using the latest master branch when building sassc?

**Comment by LyleMi** [comment]
Yes, I reproduce this with the latest master branch, and I got the same output.
