### ISSUE TITLE
Throwing error with a node-sass test on Windows

### ISSUE THREAD

**Issue by am11** [sass/libsass#586]
@mgreter, @xzyfer

When running this test in node-sass [`should report correct sourceMap in stats with renderSync`](https://github.com/sass/node-sass/blob/5c05acfc2458bd13411de2827e2fe5cf2f57c6d0/test/test.js#L315-L325) on windows, it throws this error:

``` powershell
  1) compile with stats should report correct sourceMap in stats with renderSync:
     Error: the string "Unable to allocate memory: bad allocation
" was thrown, throw an Error :)
      at Runner.fail (C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runner.js:196:11)
      at C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runner.js:455:16
      at done (C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runnable.js:206:5)
      at Test.Runnable.run (C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runnable.js:229:7)
      at Runner.runTest (C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runner.js:373:10)
      at C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runner.js:451:12
      at next (C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runner.js:298:14)
      at C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runner.js:308:7
      at next (C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runner.js:246:23)
      at Object._onImmediate (C:\Users\Adeel\Source\Repos\node-sass\node_modules\mocha\lib\runner.js:275:5)
      at processImmediate [as _immediateCallback] (timers.js:345:15)
```

I have tested further and it is working fine till this commit: https://github.com/sass/libsass/commit/f55b2d50342f97228a56a513b4cabf40996d6092. As soon as I try with the next commit (the last commit of v3.0.1): https://github.com/sass/libsass/commit/ca5f271883db61ccd1d1e1b84dd4830a2564896f, it throws the aforementioned error.

/cc @andrew

**Comment by ngryman** [comment]
Hey,

I run into the same issue with nearly the same code as @jpdesigndev.
It seems to be related to maps manipulation in `@each`.
It's also random. Commenting, uncommenting chunks of codes make the issue disappear, re-appear randomly.
